name: Build Features

on: 
  push:
    branches:
      - develop
      - feature/*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '10.x'
    - run: npm install
    - run: npm run build hewitson-dev -- --prod